### ISSUE TITLE
Feature Request: Deleting selected node(s) with Delete button

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#102]
**Expected behavior:**
1. Select a node or multiple nodes
2. Press the Delete key
3. Selected nodes should get deleted the same way as clicking on the Delete Node button

**Comment by lexaay** [comment]
Doesn't work on Mac as there's no "delete" key, its actually "backspace" (even though its says "delete" on the key). I'll accept the push request anyway, then re-open this issue separately.

**Comment by lexaay** [comment]
Need to handle "backspace" key on Mac.
