### ISSUE TITLE
Text on "-" button for actions becomes "..." in smaller windows

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#105]
**To reproduce:**
1. Create a node and open the Edit Node dialog
2. Add a Node/Fragment rule
3. Add an action
4. Resize the Edit Node dialog horizontally, eventually, the text on the "-" button for the action becomes "..." (see screenshot)

![debugging-small](https://cloud.githubusercontent.com/assets/5257832/22065591/edec1590-ddc3-11e6-84f2-d122e5e7c75a.png)

**Expected behavior:**
The text should remain as "-", which is the behavior demonstrated by the other "-" buttons on Node and Fragment Rules.

**Comment by lexaay** [comment]
Funny, this doesn't happen on a Mac... :)
