### ISSUE TITLE
Nodes are not getting properly deselected in some scenarios

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#107]
**To reproduce:**
1. Create a new node
2. Click and drag the new node to somewhere other than the original creation point (just so that the next new node does not appear directly on top of this node). There should be a red border around the current node.
3. Create another new node
4. Now two nodes have a red border around them

**Expected behavior:**
Only one node should have a red border, I recommend the newest node for this case.

**Similar cases:**
The same bug also occurs when you select a node, then copy and paste it.

**Comment by lexaay** [comment]
Doesn't happen for me - the new node is not selected in both cases (new and copy/paste). Possibly a Windows-specific issue?

**Comment by benedictleejh** [comment]
Can we get a log for this? It'd be easier to see if the right events are being generated with a log. Logs should be found `${user.home}/.hypedyn`. On Windows this should be C:\Users\<username>.

**Comment by DennisAng** [comment]
Just tested this on the latest development branch, the behavior has changed. The bug no longer occurs if the first node is click-dragged away but still occurs if the first node is not shifted at all before the creation of the second node. 

[Logs for steps below](https://github.com/narrativeandplay/hypedyn2/files/718759/hypedyn2.zip)

**To reproduce:**
1. Create a new node
2. Click the new node. There should be a red border around the current node.
3. Create another new node (This node should appear in the same spot as the previous node)
4. Click-drag one node away.
5. Now two nodes have a red border around them

**Comment by lexaay** [comment]
I can confirm this new behaviour on MacOS as well.
