### ISSUE TITLE
New Node dialog controls not responsive after changing focus from another dialog box to New Node dialog box

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#120]
**Steps to reproduce**
1. Create a new node (the New Node dialog pops up)
2. In the main window, click on New Fact (the new Fact dialog pops up)
3. Position the New Fact dialog so that it is within the bounds of the New Node dialog
4. Switch focus over from New Fact dialog to New Node dialog by clicking on the New Node dialog
5. Notice that none of the controls on the New Node dialog responds to the mouse or keyboard
6. Also, if you did step 4 correctly, now there is no way to get back to the New Fact dialog since it is being hidden by the New Node dialog and you cannot shift the dialog itself.
7. However, since the New Node dialog has focus, the escape key does not trigger the closing of the New Fact dialog box.

**Expected behavior**
The controls in the New Node dialog should be responsive.

**Useful stuff to know**
The same behavior happens if you open up the Story Properties dialog box.

**Comment by benedictleejh** [comment]
I can't replicate this on the latest development. In fact, I couldn't even switch focus from the New Fact dialog (or the Story Properties dialog) to the New node dialog box.

I tested this on Windows. Does this happen on a Mac?

**Comment by lexaay** [comment]
It also doesn't seem to be replicable on Mac. I can move the New node dialog box around, but the focus still seems to be in the New Fact dialog, and the New Fact dialog is always on top. @DennisAng does this still happen for you?

**Comment by DennisAng** [comment]
I tested this on Windows 10, 64bit and it is still happening on the latest development. I can't move the New Node dialog box around.

**Comment by lexaay** [comment]
Hmm, on Windows 10, 64 bit, when the New Fact dialogue box is up, if I try clicking on the New Node dialogue, Windows beeps at me and the focus stays on the New Fact dialogue box. If I try clicking on the main window, Windows beeps and the New Fact dialogue box blinks. So the New Fact dialogue seems to be behaving appropriately modal. :)

@DennisAng , can you show me the bug next time you're in school?

**Comment by lexaay** [comment]
Our latest theory is that this is touchscreen-related, as @DennisAng had previously tricked his computer into thinking it has a touchscreen, and only he has seen this. But I don't have access to a "real" touchscreen PC to test this theory...
