### ISSUE TITLE
Pressing the escape key when both the New Node dialog and another dialog box is open closes both dialogs.

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#121]
**Steps to reproduce**
1. Click on New Node
2. Click on New Fact
3. Press Escape, note that both dialogs close.

**Expected behavior**
The dialog with focus should close or prompt confirmation for closing.

**Comment by benedictleejh** [comment]
I can't replicate this on latest development on Windows; pressing escape closes one dialog at a time.

**Comment by lexaay** [comment]
Seems ok on Mac as well. @DennisAng do you still see this?

**Comment by DennisAng** [comment]
The bug cannot be replicated on the latest development for me as well!
