### ISSUE TITLE
Fragment at end of line removes newline when run

### ISSUE THREAD

**Issue by barefists** [narrativeandplay/hypedyn2#127]
If a line ends with a Fragment in the editor, the newline character that is supposed to be at the end of that line will be missing when the story is run.

**Comment by lexaay** [comment]
Can you attach an example?

**Comment by lexaay** [comment]
Can you let us know if this still happens with the latest build, and if so, can you upload an example?

**Comment by barefists** [comment]
Hi Alex,

 

The issue is no longer happening. Thanks! 😊

XM
