### ISSUE TITLE
fails to quit on MacOS

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#73]
On MacOS, running the built .app file, the application fails to quit (cmd-Q, window "close" button, File->Exit). Works fine when running from within IntelliJ.

**Comment by benedictleejh** [comment]
I have no idea why this is happening, and it doesn't happen on my Mac, which makes it even harder to debug. I've added a simple logging system, and logged exit events. Let's see if that gives any insight.

**Comment by lexaay** [comment]
When I do anything that calls requestExit, I get:
2016/01/15 19:06:34-308 [JavaFX Application Thread] [ERROR] Error: 
java.lang.NoSuchMethodError: org.narrativeandplay.hypedyn.events.EventBus$.SaveCancelledEvents()Lrx/lang/scala/Observable;
	at org.narrativeandplay.hypedyn.events.UiEventDispatcher$.requestExit(UiEventDispatcher.scala:261)
	at org.narrativeandplay.hypedyn.Main$$anon$6.handleQuitAction(Main.scala:212)
	at com.sun.glass.ui.mac.MacApplication$4.action(MacApplication.java:165)

This is on MacOS X 10.11.2.

**Comment by lexaay** [comment]
Sorry, not used to the Github UI, closed unintentionally...

**Comment by benedictleejh** [comment]
Can you rebuild and reinstall the whole app again? You seem to be using an old version of the API which doesn't have the new `SaveCancelledEvents` stream (which is very strange, because it shouldn't even compile if it can't find a method; unless you hotswapped the UI jar)

**Comment by lexaay** [comment]
Yes, that seems to have been the case. Doing a clean then a build fixes it. It compiled, and it ran correctly from within IntelliJ, so I'm guessing there's some bug in the Gradle packaging system.
