### ISSUE TITLE
Setting start node on another node results in two start nodes which cannot be unset

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#75]
Setting the start node on another node when you already have a start node set results in two start nodes which cannot be unset.

Create two nodes (A and B)
Set A to start node, Start node check box is now disabled and checked on A.
Set B to start node, Start node check box is now disabled and checked on B.
Double click on node A. Check box is still disabled and checked on A.
Double click on node B. Check box is still disabled and checked on B.

![bug](https://cloud.githubusercontent.com/assets/5257832/13453502/a9f81338-e08b-11e5-8458-59076775b4ed.jpg).

**Comment by lexaay** [comment]
In addition to this, when the story is run, the first node set as start node is used as the start node. On saving the story and then loading the story, both nodes are still shown as start nodes, and the first node set as start node is still used as the start node.

So basically it looks as though when a new start node is set, the previous start node is not un-set...

**Comment by benedictleejh** [comment]
I took a quick look at the problem, and it's being caused by improper setting of the update function in node editor in the UI layer, because of objects being passed by reference. I have some ideas for a fix, and I'll put something together over the weekend.
