### ISSUE TITLE
Cross origin request of local .dyn file blocked by Chrome browser

### ISSUE THREAD

**Issue by DennisAng** [narrativeandplay/hypedyn2#76]
The XMLHttpRequest of the local .dyn file is blocked by the Chrome browser which results in the start node not being displayed.

![bug](https://cloud.githubusercontent.com/assets/5257832/13453710/1b96e09a-e08d-11e5-9cb0-11ec72e7db5b.jpg)

**Comment by benedictleejh** [comment]
The rewrite of the reader will be reading from a local dyn file, and will not be done in Javascript, so this current solution isn't going to work in the rewrite.

The relevant bug report is [here](https://bugs.chromium.org/p/chromium/issues/detail?id=58151). It's not entirely clear if it'll ever be fixed.

Possible solutions:
- Use Firefox
  - Might work in other not Chrome/Chromium browsers as well
- Use [Web Server for Chrome](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en)
- Start Chrome with the command line flag `--allow-file-access-from-files`

**Comment by lexaay** [comment]
Yes, this is a workaround, and will have to be revisited when the reader is re-implemented. 

Regarding the possible solutions, using Firefox is not an option, as we can't make any assumptions about the installed browsers. I would eventually like to run a web server within the HypeDyn editor to allow for direct (socket?) communication between the reader and the editor (for debugging, for example), so in the longer term that's probably the way to go.
