### ISSUE TITLE
"follow link to" destination not saved

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#79]
The following steps lead to the destination of a "follow link to" action not being saved when the node editor is closed:

1. open a new file
2. create a new node
3. in that node, create a fragment
4. in the fragment, click "add action"
5. pull down the destination combobox - its empty as the current node isn't in the story yet
6. click "apply"
7. pull down the destination combobox - the current node is now listed
8. leave the "follow link to" action selected - don't change the selection of action type
9. select the current node
10. click "ok"
11. edit the node - the destination on the action is not set

Interestingly, if you pull down the action selection after clicking "apply", the destination **is** set. I suspect this is a similar problem to #78 i.e. it is related to which data the node editor thinks has changed and therefore bothers to save...

**Comment by benedictleejh** [comment]
I can't seem to replicate this. Can you test again on the latest code, and post the logs? My own logs are telling me that everything is happening correctly.

**Comment by lexaay** [comment]
I think the fix for #78 fixed this as well.
