### ISSUE TITLE
scrollbars not set correctly when zooming in

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#84]
When zooming _in_ on the story viewer, the scrollbars are not set correctly: scrolling all the way down does not reach the bottom of the story, and there is no horizontal scrollbar. Scrollbars are only set correctly after I move one of the nodes, at which time the extents of the story seem to be calculated correctly, and the scrollbars resize themselves appropriately.

**Comment by benedictleejh** [comment]
While I can replicate the issue, I'm not entirely sure what's causing the problem. The extents of the graph are always recalculated on changes to the zoom value. It could be a data race, and if it is, I haven't the faintest clue how to resolve it at the moment.
