### ISSUE TITLE
changes to story properties cannot be undone and do not mark file as changed

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#91]
Changes to story properties cannot be undone and do not mark file as changed.

**Comment by benedictleejh** [comment]
For sanity, I'm breaking API to fix this.

The title, author, and description will be moved into the Metadata class, so we don't have an 8 element case class for the undo. File format will remain unchanged, because breaking that is more trouble than it's worth.

**Comment by lexaay** [comment]
This doesn't seem to work. Making changes to the story properties still do not mark the file as changed, and cannot be undone.

**Comment by lexaay** [comment]
Sorry, it is working but was committed too late to make it into release 0.25beta.
