### ISSUE TITLE
hide (command-H) on Mac shows an "about" window

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#92]
On a Mac, pressing command-H to hide the app instead shows an "about" window (see attached). This is not the same window that is shown when the Help-About menu item is chosen.

![untitled-1](https://cloud.githubusercontent.com/assets/3497492/16091823/2a2d0a58-32ea-11e6-87c1-ac43f9a4e5a9.png)

**Comment by benedictleejh** [comment]
And I can't replicate this on my Mac with the latest development code. It hides as expected, and I can't quite get that about window to show up. I am, however, still on 10.10.

**Comment by lexaay** [comment]
Strange, I'm also not able to recreate it now. It must have been an interaction with something else - I had lots of applications running at the time, and also had left HypeDyn running for several days. I'll mark this as invalid.
