### ISSUE TITLE
phantom rule after deleting fragment text at the end of a node

### ISSUE THREAD

**Issue by lexaay** [narrativeandplay/hypedyn2#99]
In the attached file, edit the node "end 1", double click on the "restart" fragment, and then press the "delete" key to delete the text (and associated fragment). Now click on some other text and then click back on the place where the deleted text used to be. The deleted rule will reappear in the rule list. Now type some text in that spot. The deleted fragment reappears in the fragment list. 

This phantom rule disappears if the node is closed and reopened. If the final step above is carried out (type some text in the location of the deleted fragment) then the rule stays when the node is closed. 

This only seems to happen when the fragment is at the end of the node. My guess is that the formatting linked to the fragment has not been cleared from the zero-length insertion point. May be related to bug #57?

[deletebug.dyn2.zip](https://github.com/narrativeandplay/hypedyn2/files/681588/deletebug.dyn2.zip)

**Comment by benedictleejh** [comment]
Fixed in 89abe0b
